# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.2
  
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
      
workflows:
    example-workflow:
      jobs:
        - cypress/run:
            record: true 
            parallel: true 
            parallelism: 2 
            browser: chrome 
            command: npm run test:chrome 
            store_artifacts: false 
            yarn: false 
            attach-workspace: false 
            no-workspace: false 
            component: false 
            executor: with-chrome       

