# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.2
  browserstack-local: shawnlobo96/browserstack-local@1.0.0
  
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
      
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
    steps:
      - cypress/setup:
          build: buil-1         

          
workflows:
    practice-workflow:
      jobs:
        - example-job 
        - cypress/run:
            name: RunTest-cypress
            command: npm run test:chrome 
            record: true 
            browser: chrome             
            store_artifacts: true 
            executor: with-chrome 
            

