# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.2
  
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'      
      
workflows:
  build:
    jobs:
        - cypress/run:
            name: Practices Test Chrome
            command: npm run test:chrome
            executor: with-chrome
            browser: chrome
        - store_test_results:
            path: test-results 
      
          
